### ISSUE TITLE
PRs not being promulgated vai email

### ISSUE THREAD

**Issue by pndaly** [SAGUARO-MMA/sassy_q3c_models#3]
At today's Saguaro meeting (12/15/2022) I was made aware of a PR from Azalee. I was not notified by email of this
request. I logged in and found another request from Griffin from last August (regards setup.py). I didn't receive an
email about that either so something is not setup properly.

**Comment by griffin-h** [comment]
If you click on the "Watch" menu at the top right of this screen, you can choose to be notified for "All Activity" on this repository.
